### PR TITLE
Fix 32-bit and big-endian builds

### PR DESCRIPTION
**Pull request by darkk**
That's a few small fixes those should be easy to review.

I'm submitting them separately to shorten the next PR that'll focus on better SpeedTest reporting and MIPS32 cycle counter.

### CODE REVIEW

**Comment by darkk** [comment]
Failures are the same as they were in https://github.com/rurban/smhasher/pull/289#issuecomment-2222234036

**Comment by rurban** [comment]
macOS PMP_Multilinear.h:1421:6: error: no viable overloaded '+='
and windows should really be fixed somewhen...

**Comment by darkk** [comment]
> windows should really be fixed somewhen

Speaking of... I've got 32-bit BE, 64-big BE and 32-bit LE machines and I see lots of failures. What's the best way to deal with them? I mean, I can do "my" best, but I'd like to know your opinion before submitting PR :-)

That's usual x86_64:
```
i7-6600U(64le)$ build/SMHasher --test=VerifyAll --verbose | awk '/Verification/ {print $7}' | sort | uniq -c
      4 INSECURE
    193 PASS
     37 SKIP
```

MIPS32, LE:
```
snr(32le)$ /tmp/SMHasher --test=VerifyAll | awk '/Verification/ {print $7}' | sort | uniq -c
      3 FAIL!
      8 INSECURE
    142 PASS
     21 SKIP
```

And MIPS32, Big Endian:
```
tp842(32be)$ /tmp/SMHasher --test=VerifyAll | awk '/Verification/ {print $7}' | sort | uniq -c 
    117 FAIL!
     10 INSECURE
     26 PASS
     19 SKIP
```
